### ISSUE TITLE
Get Drupal User Information

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#11]

**Comment by thehabes** [comment]
Blocking #5

**Comment by cubap** [comment]
users.csv may be a way to align the TPEN users logged and the Drupal users. Obviously Drupal will be shut off, so we don't need to do anything but migrate the existing accounts.

**Comment by thehabes** [comment]
No longer blocking, but still an issue of its own until we can figure out script to align the information in the SQL db.  When a user comes to log in for the first time with the old email, we will have to put them through a password reset.  This should ensure ID's remain the same.  

What I still have not learned is if that Drupal Uid makes any other connection between environment and data we need to be aware of.  If not, and it was all just for Drupal stuff and all we need is the existing T-PEN UID and email, we can shim in automated password resets when User password is "DRUPAL_LOGIN" and whatever else we want to check for.

**Comment by thehabes** [comment]
It seems like the other drupal CSVs connect to user through `author uid` columns.  T-pen-projects is interesting, it has a TPEN-URI

**Comment by cubap** [comment]
Pushing this out of Sprint 2, since there is not a workflow defined for it right now.
