### ISSUE TITLE
transcription.html References

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#12]
The HTML naming convention in the newberry specific deploy is around the HTML page that represents the interface they want (newberryTrans.html, italianTranscription.html).  This means all links built with transcription.html need to be changed.

**Comment by thehabes** [comment]
newberryTrans.html now instead.  How we know whether to pick italianTranscription.html or newberryTrans.html is still a mystery.

**Comment by cubap** [comment]
punt for database changes in #12

**Comment by cubap** [comment]
see #27
