### ISSUE TITLE
updateLastActive()

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#120]
This is not being triggered in certain places anymore.  It is on heartbeat.jsp and index.jsp, which I do not think we are using in a way that sets this anymore.  It is screwing up reports.  We need to figure out when and where we want this to fire.

**Comment by thehabes** [comment]
This is already set when a user logs in.  That is probably good nuff.

**Comment by cubap** [comment]
@thehabes Okay to close?
