### ISSUE TITLE
Master Transcriptions

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#133]
There is a Master Transcriptions' option in the header for French and Italian.  This page should offer links into the Master Project for the given title if we are going to offer it.  Right now it links off to the static plain text "transcription" they have for it, which is what the Split Screen tool should be using.

**Comment by cubap** [comment]
This is how it works right now. The master transcriptions in TPEN are not really used by the platform except to copy projects, so we shouldn't change that. In the future, extracting the transcription instead of having a copy makes more sense, but that's not what happened.
