### ISSUE TITLE
project.jsp: Deleteable Project List

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#138]
Admins can delete projects here.  Contributors cannot.  Maybe just don't let either, since they can do it on My Transcriptions.  

Connected to this, the instructions "To manage a different project, select below. Clicking the X will delete your project.".  Contributors do not see the X.

**Comment by cubap** [comment]
yup. This option will be removed completely. Probably project.jsp as well. see #141
