### ISSUE TITLE
Sign Up/Invite/Mailer

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#139]
We are not yet convinced this stuff is working.  Troubleshoot it.

**Comment by cubap** [comment]
Can we put this up on prod to make sure it is doing what we expect? I think it's all there, iirc

**Comment by thehabes** [comment]
@cubap It is up on prd-01 talking to the TPEN_NL SQL database.  This is at newberry.rerum.io/paleography/.

Removed the user tied to my Gmail.  Signed up.

Did not get the E-mail.  User was in users table with a password and the correct email value.

All the redirects for a logged in/non-logged in users are there.  signup has a spot.

**Comment by cubap** [comment]
Sadly, I do not have the properties file to dig into this more, but this is the observed behavior.

login.jsp redirects to signup.jsp and they appear to behave the same. 
Addresses within slu.edu work, but external addresses fail. This no bueno.

**Comment by cubap** [comment]
changing NOTIFICATIONEMAIL to research.computing@slu.edu 'solves' it, but this isn't ideal.

**Comment by cubap** [comment]
per ITS, this is the expected behavior
