### ISSUE TITLE
saveNewTransLineServlet 500

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN-NL#14]
HTTP Status 500 - java.lang.String cannot be cast to java.lang.Integer

when saving a new column. Is this maybe a tpen line number issue? It is possible this project isn't formed as one expects.

**Comment by cubap** [comment]
http://paleo.rerum.io/TPEN-NL/newberryTrans.html?projectID=5197&p=2353 is where

**Comment by thehabes** [comment]
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	edu.slu.tpen.servlet.SaveNewTransLineServlet.doPost(SaveNewTransLineServlet.java:37)

**Comment by thehabes** [comment]
http://devstore.rerum.io/v1/id/5f89d00be4b0a2afb73aee69
Note `on` and `oa:createdBy`, gotta ensure these line up right for the production data set.  This is what I expected for the paleo.rerum.io deploy, so we should have control over it for the prd-01 deploy.
