### ISSUE TITLE
Peek Zoom Repeats and Contradicts in Help

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#143]
![image](https://user-images.githubusercontent.com/3287006/140808676-370dae3a-1d71-4cf9-a439-d41a1bdc0051.png)

ctrl + alt is "hide workspace"
ctrl + shift is "peek zoom"

They both work.

**Comment by cubap** [comment]
This is not in the current interfaces. Perhaps this is from a file within the static site?
