### ISSUE TITLE
Site index

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#146]
Right now it defaults in to index.jsp.  I think we either want to see login.jsp or my-transcriptions.html.  

Not sure what we decided on with this, but I thought we said index.jsp would go away.

**Comment by cubap** [comment]
I support keeping it, but making it more clearly an index page. No one should try to go there directly because we do not have any real support for it, so it won't even be bookmarked. The exit points should be to the static paleography homepages.
