### ISSUE TITLE
Data update from UTL

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN-NL#169]

**Comment by thehabes** [comment]
E-mail sent

**Comment by thehabes** [comment]
Files were received.  @cubap is going/went over the files to look for differences and prepare for SQL data fixes.

**Comment by cubap** [comment]
* This SQL file should update without clearing duplicate data. [tpenPaleography.txt](https://github.com/CenterForDigitalHumanities/TPEN-NL/files/9087513/tpenPaleography.txt)
* basic page updates completed on French and Italian
* several background essays updated in Italian
* no transcription updates
* lots of new users and projects for when we finally push that all in.
