### ISSUE TITLE
Transcribe on TPEN button behavior is broken

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN-NL#201]
On a page like https://french.newberry.t-pen.org/www/record.html?id=https://iiif.library.utoronto.ca/presentation/v2/paleography:1807/manifest the button links to http://newberry.t-pen.org/paleography/transcribe/Troisieme%20registre%20des%20contracts%20d'acquets%20faits%20dans%20l'etendue%20du%20fief%20et%20seigneurie%20de%20l'Epiniere which should start redirect to login and/or start/continue a transcription project. It just breaks.

![image](https://github.com/CenterForDigitalHumanities/TPEN-NL/assets/1119165/cda2f8f5-28e8-4cac-b3fd-5f822e4135fc)

**Comment by thehabes** [comment]
Decision is to patch this back end code to expect a JSONArray response from batch_create.action.  Try/catch around that parsing, and remove the initial `JSONObject.fromObject(response)`

**Comment by cubap** [comment]
@thehabes so is this finished? I can check the code but I didn't see an obvious commit

**Comment by thehabes** [comment]
Yes this is finished.  I tested by logging in at https://newberry.t-pen.org/paleography/login.jsp?referer=my-transcriptions.html

I then did a "Transcribe in TPEN" link for a Manuscript which did not exist in "my transcriptions"

I watched the server logs, and this error did not occur.  The batch create worked for each page which resulted in my project, which I was redirected to.
