### ISSUE TITLE
Copy Project Result (`copyProjectWithAnnotations.java`)

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#26]
What exactly should be happening in `/copyProjectWithAnnotations`?  Should the same thing be happening in French and Italian?  From the branch deployed at UofT in our environment, it is behaving like the first point.  Is this wrong?  How is their environment functioning now?  I am getting mixed answers and mixed results, and am completely lost.  Nowhere does it alter `cnt:chars` of annotation list resources, so it may just be a minor miracle or major coincidence it is "working" in their environment. 

- Copy of A results in B with all line parsing and text
- Copy of A results in B with line parsing but no line text
- Copy of A results in B without any line parsing and text

**Comment by cubap** [comment]
hmmmm...
It looks like this is only connected to the button on project.jsp, so something else is happening when someone "starts a transcription from Newberry". Let me look into it.

This version should be copying the transcriptions, so I don't think it is what's used.

**Comment by cubap** [comment]
I bet this is what is being used behind the `https://paleography.library.utoronto.ca/islandora/object/paleography%3A2070/transcribe` endpoint.
[CopyProjectForPracticerServlet.java](https://github.com/CenterForDigitalHumanities/TPEN-NL/blob/06e05cefb3b37c929cff6ad178f01bc572f13c30/Source%20Packages/java/edu/slu/tpen/servlet/CopyProjectForPracticerServlet.java#L47)

**Comment by cubap** [comment]
In summary, 

1. is what is and should be happening in `/copyProjectWithAnnotations`
2. is managed by `/copyProjectForPracticerServlet` and the only "button" for it is on the Manuscripts page of the paleography site
3. is an aberration and should be thrown into the abyss and removed from historical record withal.

**Comment by cubap** [comment]
@habes will close this up if he is satisfied.

**Comment by thehabes** [comment]
I have confirmed the behavior.  There are 3 servlets involved, which are all correct.  We need to ensure the UI/UX links to the correct endpoint for the desired scenario.

1. `/copyProjectAndAnnotations` requires a T-PEN project ID and results in a new project with the same line parsing and line transcriptions
2. `/copyProject` requires a T-PEN project ID and results in a new project with the same line parsing, but no line transcription
3. `/createProject` requires a IIIF Presentation API 2.1 Manifest URI and generates a "master" transcription.  It results in a new project without any line parsing and line transcriptions.
