### ISSUE TITLE
Check for expectations about Manifest/Canvas IDs

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN-NL#27]
Change to UofT locations means URIs will shift a bit. We will not neatly have `FP_000_000` and `IP_000_000` anymore. Below are Canvas IDs:

* French: `https://iiif.library.utoronto.ca/presentation/v2/paleography:1810/canvas/paleography:1853`
* Italian: `https://iiif.library.utoronto.ca/presentation/v2/italianpaleography:IP_059/canvas/italianpaleography:IP_059_001`

Manifests:

* French: `https://iiif.library.utoronto.ca/presentation/v2/paleography:1810/manifest`
* Italian: `https://iiif.library.utoronto.ca/presentation/v2/italianpaleography:IP_059/manifest`

**Comment by thehabes** [comment]
For reference,

In our deployment at http://paleo.rerum.io and with UofT's at https://italian-paleography.library.utoronto.ca/, Annotations target canvases using ID like `https://paleography.library.utoronto.ca/islandora/object/paleography:IP_003_001` or `https://paleography.library.utoronto.ca/islandora/object/paleography:723`

**Comment by cubap** [comment]
We may wind up having to do a batch update, but we'll figure that out later. The end stays the same, but the rest of the URI will probably change. `paleography.library.utoronto.ca/islandora/object/paleography:IP_003_001` => `iiif.library.utoronto.ca/presentation/v2/italianpaleography:IP_059/canvas/italianpaleography:IP_003_001`

It's okay, but will need to be addressed. (or update the query for both targets)

**Comment by thehabes** [comment]
Updated canvas prefix to `https://iiif.library.utoronto.ca/presentation/v2/` in properties file.

**Comment by cubap** [comment]
Not really a question, but good information.
