### ISSUE TITLE
Replace user authentication

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN-NL#3]
Turn off `geti()` from UofT session and use the built in TPEN session.

**Comment by thehabes** [comment]
Their DB dump does not contain user passwords or openIDs.  They are all `DRUPAL_LOGIN` because their login servlet uses drupal to generate a session token for the given user UID (this IS in the db, along with uname and email).  

The absence of passwords makes it impossible to use the generic T-PEN login system.  We would need all the current users' DRUPAL passwords, and if those passwords are encrypted, we need the decryption key.  For now, we can hack around it and let the login be Uname or email + the string "DRUPAL_LOGIN".

**Comment by cubap** [comment]
I know that, but I assumed if they had ever created a project in TPEN then there was some user created alongside their other one that we could line up. When we finally migrate, we would just need to have them "forgot password" to get a reset one and keep using it.

**Comment by cubap** [comment]
For example, I'm https://transcribe.library.utoronto.ca/1623 in the current site, so all I really need from new TPEN(NL) is that I can keep being 1623. The users.csv has "458,cubap,cubap@slu.edu" in it, so I just need to find out how to map one to the other.

**Comment by thehabes** [comment]
I see, that is a good approach.  If we are accepting there are no passwords and the user will need to set a password the first time they need to do anything, then this is not a blocking issue.

As far as lining them up, it would be a good practice to co-op a bit @cubap, so you can help me see the connection between DB and CSV quickly, and we can both know how they connect and move forward with a plan.

**Comment by thehabes** [comment]
Having looked a little deeper, I believe the connection between SQL and CSV is `email`.  Below I show the evidence that led me to this conclusion.

Drupal has its own Uid and T-PEN has it's own UID.  Anno lists are connected to T-PEN project ID and T-PEN UID.  Lines are connect to T-PEN UID.  The only consistently equal unique column between the SQL and CSV is `email`.

**Testing Notes**
- logged into https://italian-paleography.library.utoronto.ca/ as bhaberbe
- Loading project from My Transcriptions page `Prayers to Saint Jerome (italianpaleography:IP_003)` : https://transcribe.library.utoronto.ca/paleography/italianTranscription.html?projectID=5199

Transcription page `/geti` info
- UID = 1249
- uname = bhaberbe
- email = bhaberbe@slu.edu
- Italian CSV says Uid = 460

Page is IP_003_001
Canvas ID is https://paleography.library.utoronto.ca/islandora/object/paleography:IP_003_001

Anno List Info
```JSON
"@id":"http://store.rerum.io/v1/id/5efe1579d5de7d08645fdf2c",
"@type" : "sc:AnnotationList",
 "on" : "https://paleography.library.utoronto.ca/islandora/object/paleography:IP_003_001",
"isPartOf" : "5199",
"oa:createdBy" : "transcribe.library.utoronto.ca/1249",
"TPEN_NL_TESTING" : "false",
"copiedFrom" : "5170"
```
Lines are
```JSON
"@type" : "sc:Annotation",
 "on" : "https://paleography.library.utoronto.ca/islandora/object/paleography:IP_003_001#xywh=1,1,1,1",
"oa:createdBy" : "transcribe.library.utoronto.ca/1249" 

OR a different user transcribe.library.utoronto.ca/1925, the other bhaberbe.  
This is probably a bug caused by using me as a tester user and probably doesn't occur in other annotation lists for other users.
```

**Comment by thehabes** [comment]
```JSON
 select * from project where name="Prayers to Saint Jerome";
+------+------+-------------------------+-----------+-------------------------+-----------------+---------------+---------+
| grp  | id   | name                    | schemaURL | linebreakCharacterLimit | linebreakSymbol | imageBounding | partner |
+------+------+-------------------------+-----------+-------------------------+-----------------+---------------+---------+
| 4133 | 4124 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |       0 |
| 4733 | 4718 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 4738 | 4723 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 4739 | 4724 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5042 | 5012 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5062 | 5032 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5066 | 5036 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5108 | 5078 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5151 | 5121 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5171 | 5141 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5176 | 5146 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5189 | 5159 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5195 | 5165 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    4124 |
| 5200 | 5170 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |       0 |
| 5203 | 5173 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    5170 |
| 5232 | 5199 | Prayers to Saint Jerome |           |                    5000 | -               | lines         |    5170 |
+------+------+-------------------------+-----------+-------------------------+-----------------+---------------+---------+
```

**Comment by thehabes** [comment]
Ooo smoking gun https://github.com/CenterForDigitalHumanities/TPEN-NL/blob/sprint2/Source%20Packages/java/edu/slu/tpen/servlet/LoginHookServlet.java#L63

**Comment by thehabes** [comment]
Detected migrated users will now undergo an automatic password reset when they try to login for the first time using an old registered E-mail address.
