### ISSUE TITLE
CopyProjectForPracticer has no line parsing

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#43]
Be super duper positive what the the various "Start a Transcription" workflows do.  I am still skeptical.  When a user clicks "Start a Transcription" 
- If the user already has a project for this manuscript, they are directed to the transcription UI for their project
- If not, `/copyProjectWithAnnotations` fires.  This copies the master project for the given manuscript.  Each master has some parsing and transcription, which I believe we are supposed to bring over.

In the current UofT deployment, there is no path to copy one of your existing projects or the project of another user.  I believe there is no situation in which we use `/copyProject` (ForPracticer.java).  

So the only other situation natural for this instance is starting a new master project because a new "manuscript" came in.  This is `/createProject`, which requires you already have a Manifest generated around that manuscript.  

Therefore, I believe this is a wontfix.  If you want to introduce the path to copy one of your existing projects or the project of another user, that is a new feature of this instance.

**Comment by cubap** [comment]
We'll address this in the meeting... most of the master projects have little or no transcriptions and the content is almost ungrokkable because of that.

https://paleography.library.utoronto.ca/islandora/object/paleography%3A2070 has no partial transcription, but the first line on the first page suggests there is one and directs you to page 3 which is blank. This note appears to copy with the project.

https://paleography.library.utoronto.ca/islandora/object/paleography%3A418 has a long partial transcription, but only parsing is in the master project.

and on...

**Comment by thehabes** [comment]
Yep, I know it.  It as a major undertaking of Donal to go through and put something partial there for each "master".  This is something the Newberry and UofT staff was supposed to do but didn't have the effort.  And so I am sure there are some goofy things around the masters.

We will bring it up in the meeting.  I think we should have our critical user stories picked out and present it to them so we can all be in agreement about the outcomes.

- non-admin clicks "start transcribing" next to a manuscript on the manuscript list.  They do not yet have a project for that manuscript.  A project will be created.  Should the parsing and transcription come over from the master?
- non-admin clicks "start transcribing" next to a manuscript on the manuscript list.  They already have a project for the manuscript.  What happens now?
- non admin is looking at another non admins screen and really likes what they have done with their project.  They would like a copy of it.  Is this possible?
- non admin is looking at their own project and realizes they want a snapshot of this current work, and would like to continue work under a new project.  They would like to make a copy of their own project.  Is this possible?
- An admin comes across a new manuscript and they would like to add it to the manuscripts lists.  How?  How will the master parsing and transcribing be completed?
- An admin
