### ISSUE TITLE
Split Screen Direct Links - French

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#56]
Cannot load Background Essays or Partial Transcriptions.  After switching out URL patterns, direct links look like

- https://centerfordigitalhumanities.github.io/Newberry-Italian-paleography/transcript/ip_003?response_type=embed
- https://centerfordigitalhumanities.github.io/Newberry-French-paleography/essay/fp_330?response_type=embed

New static content is at
- Partial Transcriptions not yet available
- Example essay link: https://centerfordigitalhumanities.github.io/Newberry-French-paleography/essay/31?response_type=embed

Current working links on paleography prod are
- https://italian-paleography.library.utoronto.ca/content/transcript_ip_003?response_type=embed
- https://italian-paleography.library.utoronto.ca/content/about_fp_330?response_type=embed

We need to make sure we are minting the correct ID to connect the canvas displayed in the interface to the correct partial transcription and background essay.

**Comment by cubap** [comment]
These will be changed out completely. The patterns in the static site cannot be identical for a bunch of reasons, but the exchange can be automated and related to the UofT Manifest.

**Comment by thehabes** [comment]
Yep.  We had talked about this ahead of time and have reached the moment where the new static site content URL patterns have to match the patterns generated by `setIframeLinks()` and `buildIframeDirectLink()`.  It looks like you are doing `/essay/${id}` instead of `/about_${id}` and the ${id} is different from the one the interface is expecting : `utlID = currentCanvasLabel.substring(0,currentCanvasLabel.lastIndexOf("_")).toLowerCase();`

**Comment by thehabes** [comment]
Whether you generate content at expected URL patterns or I change the logic to generate the links for the new patterns is for the future, but we will have to line this up.

**Comment by cubap** [comment]
It will shift because the metadata of the manuscript right now has
```json
{ label: "Background Essay",
  value: "<p><a 
  href="https://paleography.library.utoronto.ca/content/about_fp_314">Background 
  Essay</a></p>"
}
```

in it. This will be updated by UofT to show the link to non-Drupal page.
