### ISSUE TITLE
All Essays/Partial Transcriptions Static Page

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#58]
For when there is no direct link, the Essays and Transcriptions split screen have a "see all" default.  Will a static site for all Partial Transcriptions and all Background Essays exist or will I have to use a different default.

```HTML
<iframe class="loadingIframe" id="contextualEssay" data_src="background-essays?response_type=embed">
</iframe>
https://italian-paleography.library.utoronto.ca/content/background-essays
https://paleography.library.utoronto.ca/content/background-essays

<iframe class="loadingIframe" id="partialTrans" data_src="partial_transcriptions?response_type=embed">
</iframe>
https://italian-paleography.library.utoronto.ca/content/transcriptions
https://paleography.library.utoronto.ca/content/partial_transcriptions

```

**Comment by cubap** [comment]
No. The user does not want to "see all" if one is not available. We should have a generic "Not available" page or hide the split screen option.

**Comment by thehabes** [comment]
Ok.  For a visual, here is what happens now.  It is consistent at least.

![image](https://user-images.githubusercontent.com/3287006/126506307-077aa481-11e0-4a0b-ad3e-3a726b3f1257.png)

**Comment by thehabes** [comment]
Removing the `question` label, as we have our answer.  We will design a 404 HTML page for this scenario that is useful to the user.
