### ISSUE TITLE
Invite User To T-PEN (for project) & Admin Approval

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-NL#62]
Do we still need it?  If not, let's make sure it is removed or turned off.  If it happens, digitalhumanities@slu.edu will be getting these "Approval Needed" E-mails. 

-----Original Message-----
From: TPEN@t-pen.org <TPEN@t-pen.org>
Sent: Friday, December 11, 2020 4:46 PM
To: digitalhumanities@slu.edu
Subject: new user request

Ted Nguyeb (cubap@slu.edu) has invited  Baby Fark McGeezax (B.F.McGeezax@gmail.com) to join TPEN, which needs your approval.

**Comment by cubap** [comment]
I already turned it off for main TPEN, unless you reinstated it. I assumed you had signed up for a new account on TPEN-NL, which may not be caught up completely with TPEN.

**Comment by cubap** [comment]
https://github.com/CenterForDigitalHumanities/TPEN28/blob/5e2202b6756645232dc302a36c0e23767ceadb05/src/java/user/User.java#L424

**Comment by cubap** [comment]
"Invite User" is on the list of questions for them and it may not be enabled.

**Comment by thehabes** [comment]
Cool.  At this moment, it is present at al.  `NOTIFICATIONEMAIL` is not used anywhere.

**Comment by cubap** [comment]
ahaha! Invite to TPEN isn't even on the page. We don't need to worry about it for now. I think everything is in place, but we need things off the table. Let's focus on the mailer in #107
