### ISSUE TITLE
Titles loading poorly

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN-NL#63]
This is happening in bhaberbe's My Transcriptions

**Comment by cubap** [comment]
![image](https://user-images.githubusercontent.com/1119165/117055339-aa046a80-ace0-11eb-951c-47392273b5f8.png)

**Comment by thehabes** [comment]
![image](https://user-images.githubusercontent.com/3287006/126216000-5b71891e-dae7-49b6-9374-735e365b318b.png)
