### ISSUE TITLE
Import manifest from UofT to start project

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN-NL#7]

**Comment by thehabes** [comment]
Here is a nice small one from Italian paleography production.  It is my user's `Prayers to Saint Jerome` scroll.

**Comment by thehabes** [comment]
Results in successful project creation.  Creates one empty annotation list for the one page : http://devstore.rerum.io/v1/id/5fc54559e4b04b611696f707.  Generates new TPEN ID and project is available at http://paleo.rerum.io/TPEN-NL/italianTranscription.html?projectID=5860

**Comment by thehabes** [comment]
Project title is `fromWebService, newBerry fromWebService project`

**Comment by thehabes** [comment]
Compare these for reference 

https://transcribe.library.utoronto.ca/paleography/project/5199

http://paleo.rerum.io/TPEN-NL/project/5860

**Comment by thehabes** [comment]
Looks like it only screws up `label` and `@id` so all around good news.  Depending on whether we want line content/parsing, only some small fixes to `CreateProjectServlet.java` and `ProjectServlet.java` are required.

**Comment by thehabes** [comment]
Manifest generation : 
```java
String repository = "newBerry";
String archive = "";
String city = "unknown";
String collection = "unknown";
city = request.getParameter("city");
if (null == city) {
    city = "fromWebService";
}
textdisplay.Manuscript m = null;
 JSONObject jo = resolveManifestURL(str_manifest);
 archive = jo.getString("@id");
 //create a manuscript
m = new textdisplay.Manuscript("newBerry", archive, city, city, -999);
.
.
.
String tmpProjName = m.getShelfMark() + " project";
if (request.getParameter("title") != null) {
    tmpProjName = request.getParameter("title");
}
try (Connection conn = ServletUtils.getDBConnection()) {
    conn.setAutoCommit(false);
    //This creates a master transcription, so the creating user is the leader so they can parse.
    Group newgroup = new Group(conn, tmpProjName, UID);
    Project newProject = new Project(conn, tmpProjName, newgroup.getGroupID());
.
.
.
```
We could probably be better about labels/titles/names/whatever.  `FIXME` around this.

Results in a group with one member (current logged in user) who is a `leader`.  This should be right

**Comment by thehabes** [comment]
manifest `@id` and sequence `@id` are generated programmatically by `ProjectServlet.java` and probably should not be `http://paleo.rerum.io/TPEN-NL/fromWebService, newBerry fromWebService project/sequence/normal` and  `http://paleo.rerum.io/TPEN-NL/fromWebService, newBerry fromWebService project/manifest.json`.

**Comment by cubap** [comment]
![Whiteboard 1 -01](https://user-images.githubusercontent.com/1119165/100663459-eb50b280-331b-11eb-8704-db03ad359cfe.png)

**Comment by cubap** [comment]
Yeah. This is worth saving.

**Comment by thehabes** [comment]
Issues required for proper functionality
1. #39 
2. #40 
3. #41 

Related Questions
1. #26 
2. #27
